FROM node:lts-alpine

WORKDIR /bee-queue

COPY package.json package-lock.json ./
# Installs per package-lock.json
RUN npm --version && npm ci

CMD ./tests.sh
COPY .eslintrc.json tests.sh ./

COPY test ./test/
COPY lib ./lib/
