version: '3.7'

services:

  bee-queue:
    build:
      context: .
      dockerfile: Dockerfile-tests
    environment:
    - BEE_QUEUE_TEST_REDIS=redis://redis

  redis:
    image: redis:alpine
    # wild escaping to get the shell to echo
    command: /bin/sh -c set\ -x\ &&\ redis-server\ --tcp-backlog\ 128\ --logfile\ /dev/null
    #command: redis-server --tcp-backlog 128 --logfile /dev/null
